development:
  dialect: postgres
  datasource: host=localhost dbname=postgres user=postgres password=postgres sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: postgres
  datasource: host=localhost dbname=postgres user=postgres password=postgres sslmode=disable
  dir: migrations
  table: migrations